-- lua-template-version: {{LUA_TEMPLATE_VERSION}}
-- =============================================================================
-- auto_mode.lua — Automatic interpolation control for mpv
-- Generated by mpv-interp-wizard v{{WIZARD_VERSION}}
--
-- Features:
--   - Auto-enable interpolation for SDR content
--   - HDR interpolation support (toggle with Ctrl+h)
--   - Hot-reload when display changes (60Hz <-> 120Hz)
--   - Manual toggle with Ctrl+i
--   - Dual backend: VapourSynth RIFE (AI) / FRUC Vulkan (hardware NVOF)
--   - Toggle backend with Ctrl+b (when both available)
--   - OSD status display with Ctrl+Shift+d
-- =============================================================================

-- ---- Configuration ---------------------------------------------------------
local BACKEND_MODE   = "{{BACKEND_MODE}}"       -- "vapoursynth" | "fruc_vulkan"
local FRUC_ELIGIBLE  = {{FRUC_ELIGIBLE}}         -- true if GPU supports FRUC Vulkan
local INTERP_FILTER_VS   = "vapoursynth=~~/interpolation.vpy:buffered-frames={{BUFFERED_FRAMES}}:concurrent-frames={{CONCURRENT_FRAMES}}"
local INTERP_FILTER_FRUC = "fruc_vulkan"
local SET_HZ_SCRIPT  = mp.find_config_file("set_display_hz.ps1")
local HDR_INTERPOLATION = {{HDR_INTERPOLATION}}  -- true = interpolate HDR; false = Hz switch

-- ---- State -----------------------------------------------------------------
local original_hz = nil
local hz_changed  = false
local interp_mode = "auto"   -- "auto", "force_on", "force_off"
local last_display_fps = nil
local active_backend = BACKEND_MODE  -- tracks the currently active backend

-- ---- Backend helpers -------------------------------------------------------
local function get_filter()
    if active_backend == "fruc_vulkan" then
        return INTERP_FILTER_FRUC
    else
        return INTERP_FILTER_VS
    end
end

local function backend_label()
    if active_backend == "fruc_vulkan" then
        return "FRUC Vulkan (hardware)"
    else
        return "VapourSynth RIFE (AI)"
    end
end

-- ---- HDR detection ---------------------------------------------------------
local function is_hdr()
    local t = mp.get_property("video-params/transfer") or ""
    local p = mp.get_property("video-params/primaries") or ""
    return t:find("pq") ~= nil
        or t:find("hlg") ~= nil
        or t:find("smpte2084") ~= nil
        or p:find("bt.2020") ~= nil
end

-- ---- Hz mapping for HDR pass-through (when interpolation is OFF) -----------
local function fps_to_hz(fps)
    if     fps >= 23   and fps < 24.5 then return 24
    elseif fps >= 24.5 and fps < 26   then return 25
    elseif fps >= 29   and fps < 31   then return 30
    elseif fps >= 47   and fps < 51   then return 50
    elseif fps >= 59   and fps < 61   then return 60
    elseif fps >= 119  and fps <= 121 then return 120
    end
    return nil
end

local function set_hz(hz)
    if not SET_HZ_SCRIPT then return false end
    local cmd = string.format(
        'powershell -ExecutionPolicy Bypass -WindowStyle Hidden -File "%s" -Hz %d',
        SET_HZ_SCRIPT, hz
    )
    return os.execute(cmd)
end

-- ---- Interpolation control -------------------------------------------------
local function interp_active()
    local vf = mp.get_property("vf") or ""
    return vf:find("vapoursynth", 1, true) ~= nil
        or vf:find("fruc_vulkan", 1, true) ~= nil
end

local function get_active_filter_string()
    -- Returns the filter string currently in use (for removal)
    local vf = mp.get_property("vf") or ""
    if vf:find("fruc_vulkan", 1, true) then
        return INTERP_FILTER_FRUC
    elseif vf:find("vapoursynth", 1, true) then
        return INTERP_FILTER_VS
    end
    return nil
end

local function enable_interp()
    if not interp_active() then
        local filter = get_filter()
        local ok, err = pcall(function()
            mp.commandv("vf", "add", filter)
        end)
        if not ok then
            mp.msg.warn("Failed to enable " .. active_backend .. ": " .. tostring(err))
            -- Fallback: if VapourSynth failed and FRUC is available, try FRUC
            if active_backend == "vapoursynth" and FRUC_ELIGIBLE then
                mp.msg.info("Attempting fallback to FRUC Vulkan...")
                active_backend = "fruc_vulkan"
                local ok2, err2 = pcall(function()
                    mp.commandv("vf", "add", INTERP_FILTER_FRUC)
                end)
                if ok2 then
                    mp.osd_message("RIFE falló → Fallback: FRUC Vulkan (hardware)", 4)
                    return true
                else
                    mp.msg.error("FRUC Vulkan fallback also failed: " .. tostring(err2))
                    active_backend = "vapoursynth"  -- restore original
                    return false
                end
            end
            return false
        end
        return true
    end
    return true
end

local function disable_interp()
    local current = get_active_filter_string()
    if current then
        pcall(function()
            mp.commandv("vf", "remove", current)
        end)
    end
end

-- ---- Core logic: decide what to do based on content + mode -----------------
local function apply_mode()
    local fps    = mp.get_property_number("container-fps") or 24
    local hdr    = is_hdr()

    if interp_mode == "force_off" then
        disable_interp()
        -- For HDR: switch Hz to match content
        if hdr then
            local hz = fps_to_hz(fps)
            if hz then
                if not original_hz then
                    original_hz = mp.get_property_number("display-fps") or 60
                end
                if set_hz(hz) then hz_changed = true end
                mp.osd_message(string.format("Interpolación: OFF | HDR %dfps → %dHz", math.floor(fps + 0.5), hz), 3)
            else
                mp.osd_message(string.format("Interpolación: OFF | HDR %dfps", math.floor(fps + 0.5)), 2)
            end
        else
            mp.osd_message("Interpolación: OFF", 2)
        end
        return
    end

    if interp_mode == "force_on" then
        enable_interp()
        if hz_changed and original_hz then
            set_hz(math.floor(original_hz))
            hz_changed = false
        end
        mp.osd_message("Interpolación: ON (forzado) | " .. backend_label(), 2)
        return
    end

    -- AUTO mode
    if hdr and not HDR_INTERPOLATION then
        -- HDR with interpolation disabled: Hz switch
        disable_interp()
        local hz = fps_to_hz(fps)
        if hz then
            if not original_hz then
                original_hz = mp.get_property_number("display-fps") or 60
            end
            if set_hz(hz) then hz_changed = true end
            mp.osd_message(string.format("HDR %dfps → %dHz | Interp OFF (Ctrl+h para activar)", math.floor(fps + 0.5), hz), 3)
        else
            mp.osd_message(string.format("HDR %dfps | Interp OFF", math.floor(fps + 0.5)), 2)
        end
    else
        -- SDR or HDR with interpolation enabled: interpolate
        if hz_changed and original_hz then
            set_hz(math.floor(original_hz))
            hz_changed = false
        end
        enable_interp()
        local mode_label = hdr and "HDR" or "SDR"
        local display = mp.get_property_number("display-fps") or 60
        local multi = math.max(2, math.ceil(display / fps))
        mp.osd_message(string.format(
            "%s %dfps → %dfps (×%d) | %s | Display: %dHz",
            mode_label, math.floor(fps + 0.5), math.floor(fps * multi + 0.5), multi,
            backend_label(), math.floor(display + 0.5)
        ), 3)
    end
end

-- ---- Events ----------------------------------------------------------------
mp.register_event("file-loaded", function()
    interp_mode = "auto"
    active_backend = BACKEND_MODE  -- reset to configured default on new file
    apply_mode()
end)

-- Hot-reload: detect display change (e.g., moving window between monitors)
mp.observe_property("display-fps", "number", function(_, val)
    if val and val > 0 then
        if last_display_fps and math.abs(val - last_display_fps) > 1 then
            -- Display changed — reconfigure
            mp.msg.info(string.format("Display changed: %.0fHz → %.0fHz, reconfiguring", last_display_fps, val))
            -- Remove and re-add filter to force recalculation with new display_fps
            if interp_active() then
                disable_interp()
                -- Small delay to let VapourSynth clean up
                mp.add_timeout(0.5, function()
                    apply_mode()
                end)
            end
        end
        last_display_fps = val
    end
end)

mp.register_event("shutdown", function()
    if hz_changed and original_hz then
        set_hz(math.floor(original_hz))
    end
end)

-- ---- Key bindings ----------------------------------------------------------
-- Ctrl+i: Toggle interpolation ON/OFF
mp.add_key_binding("Ctrl+i", "toggle-interp", function()
    if interp_mode == "force_off" then
        interp_mode = "auto"
    else
        interp_mode = "force_off"
    end
    apply_mode()
end)

-- Ctrl+Shift+i: Force interpolation ON (even if auto would disable it)
mp.add_key_binding("Ctrl+Shift+i", "force-interp", function()
    if interp_mode == "force_on" then
        interp_mode = "auto"
    else
        interp_mode = "force_on"
    end
    apply_mode()
end)

-- Ctrl+h: Toggle HDR interpolation ON/OFF (persistent for session)
mp.add_key_binding("Ctrl+h", "toggle-hdr-interp", function()
    HDR_INTERPOLATION = not HDR_INTERPOLATION
    local state = HDR_INTERPOLATION and "ON" or "OFF (Hz switch)"
    mp.osd_message("HDR Interpolación: " .. state, 3)
    apply_mode()
end)

-- Ctrl+b: Toggle backend (VapourSynth RIFE <-> FRUC Vulkan)
mp.add_key_binding("Ctrl+b", "toggle-backend", function()
    if not FRUC_ELIGIBLE then
        mp.osd_message("FRUC Vulkan no disponible (requiere RTX 30+)", 3)
        return
    end
    -- Remove current filter
    disable_interp()
    -- Switch backend
    if active_backend == "vapoursynth" then
        active_backend = "fruc_vulkan"
    else
        active_backend = "vapoursynth"
    end
    -- Re-apply
    mp.add_timeout(0.3, function()
        if interp_mode ~= "force_off" then
            apply_mode()
        else
            mp.osd_message("Backend: " .. backend_label() .. " (interp OFF)", 3)
        end
    end)
end)

-- Ctrl+Shift+d: Show diagnostic info
mp.add_key_binding("Ctrl+Shift+d", "show-interp-info", function()
    local fps     = mp.get_property_number("container-fps") or 0
    local display = mp.get_property_number("display-fps") or 0
    local hdr     = is_hdr() and "HDR" or "SDR"
    local active  = interp_active() and "ON" or "OFF"
    local multi   = fps > 0 and math.max(2, math.ceil(display / fps)) or 0
    local w       = mp.get_property_number("width") or 0
    local h       = mp.get_property_number("height") or 0

    mp.osd_message(string.format(
        "[%s] %s %dx%d | %dfps → %dfps (×%d)\nDisplay: %.0fHz | Interp: %s | Mode: %s\nBackend: %s | FRUC: %s\nHDR interp: %s | Ctrl+i=toggle Ctrl+b=backend Ctrl+h=HDR",
        active_backend == "fruc_vulkan" and "FRUC" or "RIFE",
        hdr, w, h,
        math.floor(fps + 0.5), math.floor(fps * multi + 0.5), multi,
        display, active, interp_mode,
        backend_label(),
        FRUC_ELIGIBLE and "disponible" or "no disponible",
        HDR_INTERPOLATION and "ON" or "OFF"
    ), 5)
end)
