# sethz-template-version: {{SETHZ_TEMPLATE_VERSION}}
# =============================================================================
# set_display_hz.ps1 — Change monitor refresh rate via Windows API
# Used by auto_mode.lua for HDR pass-through (match Hz to content fps).
# Generated by mpv-interp-wizard v{{WIZARD_VERSION}}
#
# Usage: powershell -ExecutionPolicy Bypass -File set_display_hz.ps1 -Hz 24
# =============================================================================
param(
    [Parameter(Mandatory)][int]$Hz,
    [string]$Display = "{{DISPLAY_DEVICE}}"   # Empty = primary
)

Add-Type @"
using System;
using System.Runtime.InteropServices;

public class DisplaySettings {
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
    public struct DEVMODE {
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)]
        public string dmDeviceName;
        public short dmSpecVersion;
        public short dmDriverVersion;
        public short dmSize;
        public short dmDriverExtra;
        public int dmFields;
        public int dmPositionX;
        public int dmPositionY;
        public int dmDisplayOrientation;
        public int dmDisplayFixedOutput;
        public short dmColor;
        public short dmDuplex;
        public short dmYResolution;
        public short dmTTOption;
        public short dmCollate;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)]
        public string dmFormName;
        public short dmLogPixels;
        public int dmBitsPerPel;
        public int dmPelsWidth;
        public int dmPelsHeight;
        public int dmDisplayFlags;
        public int dmDisplayFrequency;
        public int dmICMMethod;
        public int dmICMIntent;
        public int dmMediaType;
        public int dmDitherType;
        public int dmReserved1;
        public int dmReserved2;
        public int dmPanningWidth;
        public int dmPanningHeight;
    }

    [DllImport("user32.dll", CharSet = CharSet.Ansi)]
    public static extern int EnumDisplaySettingsA(string lpszDeviceName, int iModeNum, ref DEVMODE lpDevMode);

    [DllImport("user32.dll", CharSet = CharSet.Ansi)]
    public static extern int ChangeDisplaySettingsExA(string lpszDeviceName, ref DEVMODE lpDevMode, IntPtr hwnd, int dwflags, IntPtr lParam);

    public const int ENUM_CURRENT_SETTINGS = -1;
    public const int CDS_UPDATEREGISTRY = 0x01;
    public const int DM_DISPLAYFREQUENCY = 0x400000;
}
"@

$devName = if ($Display) { $Display } else { $null }

$dm = New-Object DisplaySettings+DEVMODE
$dm.dmSize = [System.Runtime.InteropServices.Marshal]::SizeOf($dm)

$ok = [DisplaySettings]::EnumDisplaySettingsA($devName, [DisplaySettings]::ENUM_CURRENT_SETTINGS, [ref]$dm)
if ($ok -eq 0) { Write-Error "Failed to read current display settings"; exit 1 }

$oldHz = $dm.dmDisplayFrequency
if ($oldHz -eq $Hz) { Write-Host "Already at ${Hz}Hz"; exit 0 }

$dm.dmDisplayFrequency = $Hz
$dm.dmFields = [DisplaySettings]::DM_DISPLAYFREQUENCY

$result = [DisplaySettings]::ChangeDisplaySettingsExA($devName, [ref]$dm, [IntPtr]::Zero, [DisplaySettings]::CDS_UPDATEREGISTRY, [IntPtr]::Zero)

if ($result -eq 0) {
    Write-Host "Changed ${oldHz}Hz -> ${Hz}Hz"
    exit 0
} else {
    Write-Error "ChangeDisplaySettingsEx failed with code $result"
    exit 1
}
